change error messages

diff --git a/tool/multiaffinity b/tool/multiaffinity
--- a/tool/multiaffinity
+++ b/tool/multiaffinity
@@ -104,15 +104,15 @@ mkdir -p $TMPFILE/tool/input; mkdir -p $TMPFILE/tool/input/layers; mkdir -p $TMP
 if [ -z ${output_dir+x} ]; then echo "-o is obligatory"; exit 1; fi
 ## Counts files
 if [ -z ${counts+x} ]; then echo "-c is obligatory"; exit 1; fi
-for i in "${counts[@]}"; do if grep -q "," ${i}; then cp ${i} $TMPFILE/tool/input/data/counts; else echo "Use ',' as a separator in the counts inputs"; exit 1; fi; done
+for i in "${counts[@]}"; do if grep -q "," ${i}; then cp ${i} $TMPFILE/tool/input/data/counts; else echo "Error reading count files"; exit 1; fi; done
 ## Metadata files
 if [ -z ${metadata+x} ]; then echo "-m is obligatory"; exit 1; fi
-for i in "${metadata[@]}"; do if grep -q "," ${i}; then cp ${i} $TMPFILE/tool/input/data/metadata; else echo "Use ',' as a separator in the metadata inputs"; exit 1; fi; done
+for i in "${metadata[@]}"; do if grep -q "," ${i}; then cp ${i} $TMPFILE/tool/input/data/metadata; else echo "Error reading metadata files"; exit 1; fi; done
 ## Network files
 if [ -z ${network+x} ]; then 
   cp -a $TMPFILE/tool/bin/Communities/sample_network/. $TMPFILE/tool/input/layers/
 else
-  for i in "${network[@]}"; do if grep -q "," ${i}; then cp ${i} $TMPFILE/tool/input/layers; else echo "Use ',' as a separator in the layers inputs"; exit 1; fi; done;fi
+  for i in "${network[@]}"; do if grep -q "," ${i}; then cp ${i} $TMPFILE/tool/input/layers; else echo "Error reading network layers files"; exit 1; fi; done;fi
 
 pushd $TMPFILE >& /dev/null; cd tool/
 
